### PR TITLE
cabalized build

### PR DESCRIPTION
**Pull request by abailly**
- Added `cinder.cabal` file, cinder now builds as a cabal package and could be used as "normal" package dependencies from fay
- Fixed a couple of minor build issues

BTW, I wonder what's current status of cinder. Looks like it has not moved in a year or so... But it seems pretty cool and I would like to use it for new projects and possibly improve it.

### CODE REVIEW

**Comment by bergmark** [comment]
Sweet! This has been on my personal todo list for a while now, thanks!

**Comment by crooney** [comment]
Hey abailly,

Chris here. I wrote cinder for an SVG project which never came together. I
didn't realize anybody had even started using it, much less still was. I am
more than happy to actively maintain it, if there is a user base, no matter
how small. Your contriburions are most welcome (I've given you commit
access). I've got to deal with a death for the next couple days, then will
be in touch about it.

Cheers,

chris

On Thu, May 8, 2014 at 10:49 AM, Arnaud Bailly notifications@github.comwrote:

> - Added cinder.cabal file, cinder now builds as a cabal package and
>   could be used as "normal" package dependencies from fay
> - Fixed a couple of minor build issues
> 
> BTW, I wonder what's current status of cinder. Looks like it has not moved
> in a year or so... But it seems pretty cool and I would like to use it for
> 
> ## new projects and possibly improve it.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/abailly/cinder master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/crooney/cinder/pull/1
> Commit Summary
> - added .cabal file
> - cabal builds works
> - fix version according to what's been already released
> 
> File Changes
> - _A_ cinder.cabalhttps://github.com/crooney/cinder/pull/1/files#diff-0(44)
> - _M_ src/Cinder/DOM.hshttps://github.com/crooney/cinder/pull/1/files#diff-1(9)
> - _M_ src/Cinder/SVG.hshttps://github.com/crooney/cinder/pull/1/files#diff-2(18)
> - _M_ src/Control/Fay.hshttps://github.com/crooney/cinder/pull/1/files#diff-3(4)
> - _M_ util/combos.shhttps://github.com/crooney/cinder/pull/1/files#diff-4(18)
> 
> Patch Links:
> - https://github.com/crooney/cinder/pull/1.patch
> - https://github.com/crooney/cinder/pull/1.diff
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/crooney/cinder/pull/1
> .

## 

_Second base is known for many things, one of which is it isn't third
base.-- Matthew Kory_

**Comment by abailly** [comment]
Hi Chris,
Thanks for the trust. I stumbled upon cinder while I was looking for combinators library to do some HTML markup sanely, without resorting to concatenating Texts, something along the line of hiccup in clojure, or blaze on server-side Haskell. This looks cool and I was pretty much excited by the demo animations. Trying to kill two birds with a single stone, I started to integrate cinder into a pet project I work on with @mostalive, https://github.com/mostalive/yesod-splittest while at the same time thinking of using it to generate animations for a talk I shall give on raft (https://github.com/abailly/raft-for-dummies). 

This project looks really cool and a great foundation for Fay-based client-side markup generation. Would like to know @bergmark thoughts about this too :-)

Arnaud

**Comment by crooney** [comment]
Ok, cool. Cinder is a play on the word blaze, and some of the operators
designed to look like it, as far as was convenient.

I've given @bergmark commit as well, as I live in the 3rd world, and my
service provider can be offline for days at a time, and I'd hate to be even
an inadvertant holdup.

Cheers

On Thu, May 8, 2014 at 1:22 PM, Arnaud Bailly notifications@github.comwrote:

> Hi Chris,
> Thanks for the trust. I stumbled upon cinder while I was looking for
> combinators library to do some HTML markup sanely, without resorting to
> concatenating Texts, something along the line of hiccup in clojure, or
> blaze on server-side Haskell. This looks cool and I was pretty much excited
> by the demo animations. Trying to kill two birds with a single stone, I
> started to integrate cinder into a pet project I work on with @mostalivehttps://github.com/mostalive,
> https://github.com/mostalive/yesod-splittest while at the same time
> thinking of using it to generate animations for a talk I shall give on raft
> (https://github.com/abailly/raft-for-dummies).
> 
> This project looks really cool and a great foundation for Fay-based
> client-side markup generation. Would like to know @bergmarkhttps://github.com/bergmarkthoughts about this too :-)
> 
> Arnaud
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/crooney/cinder/pull/1#issuecomment-42582355
> .

## 

_Second base is known for many things, one of which is it isn't third
base.-- Matthew Kory_

**Comment by bergmark** [comment]
I've just briefly looked at this project, not actually used it for anything. I've been using fay-jquery to do "templating". Using cinder as a first step and then using jquery on the result to create bindings might be nicer. It gives a clear separation and rendering on the server too would be nice!

A couple of things that might be nice is to integrate Cinder's DOM module into `fay-dom` to remove some duplication, and to switch `String` into `fay-text` since it's more efficient and less quirky. The latter should be trivial, see https://github.com/faylang/fay-dom/commit/6183b24d968e7171006312610bd3e1b2fe9fc8e4 for instance.

... and to just put this on hackage soon so people can find it :)

**Comment by abailly** [comment]
@bergmark Yes, that's exactly what I had in mind. I am currently converting to Text. Not complex, but a bit tedious (unless I am missing something obvious?). Next step would be to ensure build takes care of some generation stuff that is currently undertook with shell scripts. Was thinking about using TH to do that. And merging DOM related stuff in fay-dom is next on my list, given we are already using fay-dom. 

I have no idea how one put something on hackage, so that would be a great opportunity to learn.

Something I have in mind, which is a bit more ambitious though, is developing something like [Om](https://github.com/swannodette/om) possibly integrating some ideas from MVC. Do you know if there is already an effort in that direction in Fay?

**Comment by bergmark** [comment]
It should be
- Add `{-# LANGUAGE OverloadedStrings, RebindableSyntax #-}`
- `Import Fay.Text`
- Replace `String` => `Text`
- Maybe switch list functions to the text counter-parts

I don't think anyone has experimented with using TH at all with Fay so I'm not sure how hard it is. Is it as simple as invoking ghc with the appropriate flags to dump the TH output and then just compile that?

Some people showed interest in making angular bindings, https://github.com/faylang/fay-angular but it doesn't seem like there has been much progress. the defaults angular uses seem to be pretty magical, such as expecting function arguments with certain parameter names instead of using positional arguments, something that Fay can't generate through the FFI as it stands.

But yeah, I'm personally more interested in React but I've only glanced at it, not sure if anyone has tried to write any bindings to Fay for it.

**Pull request merged**
