### PR TITLE
Replace String with Text

### PR DESCRIPTION
**Pull request by abailly**
- Replace all use of String with Fay.Text Text implementation to provide native JS strings. 
- did some cleanup of compiler warnings in the process

### CODE REVIEW

**Comment by bergmark** [comment]
Did you also get push access or was it just me? Can't figure out how to check...

Anyway, looks good as a first step!

I'm not too fond of the `toText` business but the real issue is that the functions are overly polymorphic. Does it make sense that they accept anything other than `Text`? It's possible to constrain the types a bit more if they can be accepted as is, like we've done in fay-jquery (though the need for the `Fay$$_` force call makes it ugly!):

```
class Selectable a

instance Selectable Text
instance Selectable Element
instance Selectable JQuery

select :: Selectable a => a -> Fay JQuery
select = ffi "jQuery(Fay$$_(%1))"
```

otherwise i think it makes sense to have the caller do the conversion explicitly

**Comment by abailly** [comment]
I have push access, but having four eyes looking stuff has often saved me time and effort...

You are right, I just ported the previous `show` adding the `pack` to make it work. Having a "marker" type class sounds like a good idea, will try to do that.

**Comment by bergmark** [comment]
Ok, I'm happy to review!

**Comment by crooney** [comment]
Hey fellas, I'm back online and have some cycles to spare. Any feature
requests while I'm ready to go?

On Mon, May 12, 2014 at 5:18 PM, Adam Bergmark notifications@github.comwrote:

> Ok, I'm happy to review!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/crooney/cinder/pull/2#issuecomment-42892871
> .

## 

_Second base is known for many things, one of which is it isn't third
base.-- Matthew Kory_

**Comment by abailly** [comment]
Hi Chris,
We quickly discussed the following with Adam:
- merge the DOM stuff in cinder with what’s done in fay-dom as there is some duplication 
- publish to hackage 
- upgrade the examples (did not have time to review them).

Cheers,
Arnaud

**Comment by crooney** [comment]
Yeah, that's pretty much what I figured. Banging on the examples right now.
Will look at DOM stuff tomorrow or Friday.

Cheers

On Thu, May 15, 2014 at 12:06 AM, Arnaud Bailly notifications@github.comwrote:

> Hi Chris,
> We quickly discussed the following with Adam:
> - merge the DOM stuff in cinder with what's done in fay-dom as there is
>   some duplication
> - publish to hackage
> - upgrade the examples (did not have time to review them).
> 
> Cheers,
> Arnaud
> 
> On 15 May 2014, at 02:45, Chris Rooney notifications@github.com wrote:
> 
> > Hey fellas, I'm back online and have some cycles to spare. Any feature
> > requests while I'm ready to go?
> > 
> > On Mon, May 12, 2014 at 5:18 PM, Adam Bergmark notifications@github.comwrote:
> > 
> > > Ok, I'm happy to review!
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/crooney/cinder/pull/2#issuecomment-42892871>
> > > .
> > 
> > ## 
> > 
> > *Second base is known for many things, one of which is it isn't third
> > 
> > ## base.-- Matthew Kory*
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/crooney/cinder/pull/2#issuecomment-43167830
> .

## 

_Second base is known for many things, one of which is it isn't third
base.-- Matthew Kory_

**Comment by abailly** [comment]
Great! And thanks a lot for this project :-)

**Pull request merged**
